### ISSUE TITLE
i cant see my actions on wakatime though plugin was installed correctly 

### ISSUE THREAD

**Issue by NikosEfthias** [wakatime/netbeans-wakatime#11]
all other editors i use work fine but netbeans

**Comment by alanhamlett** [comment]
Do you have any error messages from netbeans log?

**Comment by NikosEfthias** [comment]
i am quite new to eclipse i have no idea how to see the log file @alanhamlett

**Comment by alanhamlett** [comment]
Which editor is working and which is not working?

If Eclipse is not working, check it's logs from Window -> Show View -> Error Log.

If Netbeans is not working, check it's logs from View -> IDE Log.

**Comment by NikosEfthias** [comment]
brackets vscode and shell work well only netbeans i face this issue

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/di6dPKk.png)

**Comment by alanhamlett** [comment]
Does the new version 4.0.6 fix the bug?

**Comment by NikosEfthias** [comment]
i get this error when i open the editor 
![](http://i.imgur.com/nxNLJBX.png)

**Comment by NikosEfthias** [comment]
http://statistics.netbeans.org/analytics/exception.do?id=818292 here's the error report for full system information

**Comment by alanhamlett** [comment]
That error report is from the old plugin version. After updating to v4.0.6 do you still get that exception?

**Comment by NikosEfthias** [comment]
now seems working thank you for solution
