### ISSUE TITLE
No Option to insert API Key

### ISSUE THREAD

**Issue by benyaminl** [wakatime/netbeans-wakatime#13]
Hello, I'm on Netbean 8.1 and when installing, no option to insert the key, until now even I do code it's not sending a message box or other about asking API key.. any ideas?

**Comment by benyaminl** [comment]
@alanhamlett Sorry Seems like the waka time API is synced across IDE.

**Comment by CraicOverflow89** [comment]
I'm having the same issue - plugin installed (correctly?) on Netbeans 8.2 but no option to enter API key? Where did you go to enter the key?

**Comment by navalinovian** [comment]
you can manually input API key in netbeans by following step : tools -> option -> wakatime -> enter API key -> ok.
