### ISSUE TITLE
API key form was not prompted after the plugin instalation

### ISSUE THREAD

**Issue by erdrborges** [wakatime/netbeans-wakatime#14]
I'm using Netbeans 8.2 alongside with netbeans-wakatime-v4.0.8.nbm and after the plugin instalation and the reboot of Netbeans, the API key form was not prompted and I can't figure out how can I manually enter the API Key for Wakatime Sync.

Thanks in advance for the help.

**Comment by alanhamlett** [comment]
From Netbeans -> Preferences there should be a WakaTime tab where you can enter your [api key](https://wakatime.com/settings/api-key):

![netbeans-preferences](https://user-images.githubusercontent.com/522344/38470596-0e228e02-3b1a-11e8-85ef-5873b2437c6d.gif)

**Comment by erdrborges** [comment]
Thanks for the reply . I've entered my API key and now the WakaTime is working.
