### ISSUE TITLE
The wakatime plugin stopped working for netbeans

### ISSUE THREAD

**Issue by antag0n1st** [wakatime/netbeans-wakatime#15]
The wakatime plugin stopped working for netbeans , its been 6 days since it has stopped working.

**Comment by gandarez** [comment]
@antag0n1st  Don't you see any time logged into your dashboard? 

Also please attach any log here in this issue

```
Netbeans logs to it's own log file (View -> IDE Log).
After the plugin passes control to wakatime-cli, logs go to the common ~/.wakatime.log file.
```

**Comment by alanhamlett** [comment]
@antag0n1st looks like it's working again, were you able to get it working by re-installing or another method?
