### ISSUE TITLE
hi, I have issue with wakatime,

### ISSUE THREAD

**Issue by BRODYAGA01** [wakatime/netbeans-wakatime#17]
I have installed the plugin correctly but I can't see my stats on Dashboard of Wakatime. Below picture of issue. How to fix it? 
thank you.best regards
![issue](https://user-images.githubusercontent.com/48329595/73133802-18627380-402e-11ea-99cc-412df28c5a1e.png)

**Comment by BrianKnoblauch** [comment]
Any updates on this?  I'm having the same problem.  Same log entries.  Wakatime doesn't seem to log anything itself, so does not appear to be starting.  Also does not show up in the installed plugin list.  If I try to install, it reports as already being installed.  Our development platform is Netbeans 8.2 on Oracle JDK 8u202x64.

**Comment by alanhamlett** [comment]
Fixed in v4.0.9.
