### ISSUE TITLE
Netbeans IDE pluggin issue

### ISSUE THREAD

**Issue by Chinecherem** [wakatime/netbeans-wakatime#20]
I installed the wakatime netbeans plugin  but noticed the wizard did not give me a prompt to enter authentication key. The installation was successful and I can see the plugin in my IDE but my wakatime dashboard is not showing my coding activity on netbeans.
I have uninstalled and reinstalled again, same experience. Is their a way you can help?

**Comment by alanhamlett** [comment]
Fixed in v4.0.9.

**Comment by Jeffrey0710** [comment]
I have the same problem with v.4.0.10, what did you do?

**Comment by Jeffrey0710** [comment]
> I installed the wakatime netbeans plugin but noticed the wizard did not give me a prompt to enter authentication key. The installation was successful and I can see the plugin in my IDE but my wakatime dashboard is not showing my coding activity on netbeans.
> I have uninstalled and reinstalled again, same experience. Is their a way you can help?

I have the same problem with v.4.0.10, what did you do?
