### ISSUE TITLE
API key form was not be popped up after the plugin installation

### ISSUE THREAD

**Issue by Hephaest** [wakatime/netbeans-wakatime#22]
### Environment information
OS: Windows 10 64-bit
NetBeans IDE: 8.2 RC
JDK: 1.8.u271
Plugin version: netbeans-wakatime-v4.0.10

**Comment by alanhamlett** [comment]
@Hephaest do you possibly have another WakaTime extension installed for a different IDE? The plugins detect the api key from a shared config file, so that would prevent it from prompting.

Related to #13 and #14.

**Comment by Hephaest** [comment]
Thanks for your reply. I got the inner knowledge about that from the [answer](https://github.com/wakatime/netbeans-wakatime/issues/13#issuecomment-419305283)
