### ISSUE TITLE
Plugin not found in Netbeans

### ISSUE THREAD

**Issue by MohamedZaahran** [wakatime/netbeans-wakatime#25]
I have installed the plugin, put my API Key, but it is not found under Tools >> Plugins >> Settings, what is the URL for it in order to be active and appear in my dashboard?
@alanhamlett

**Comment by alanhamlett** [comment]
The config file is located at:

`~/.wakatime.cfg`

If your api key is correct there and the plugin is installed in Netbeans, then it should work even though the settings menu has stopped working in a recent Netbeans update.
