### ISSUE TITLE
IDE is frozen if Python isn't in the system PATH (restart fixes it)

### ISSUE THREAD

**Issue by jonathanlermitage** [wakatime/netbeans-wakatime#3]
Hi,
The IDE freezes when the plugin is installed, just after the dialog that indicates Python is not on the system's PATH.
Killing and restarting NetBeans resolves the problem.

During the freeze, there's nothing relevant in NB logs:

INFO [WakaTime]: Initializing WakaTime plugin v3.0.1 (https://wakatime.com/)
INFO [WakaTime]: Downloading and installing wakatime-cli ...
INFO [WakaTime]: Finished downloading and installing wakatime-cli.
SEVERE [WakaTime]: WakaTime requires Python to be installed.
INFO [WakaTime]: Checking for updates...
WARNING [org.netbeans.modules.progress.spi.InternalHandle]: Cannot call progress on a task that was never started at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.refresh(UpdateUnitProviderImpl.java:177)
WARNING [org.netbeans.modules.progress.spi.InternalHandle]: Cannot call progress on a task that was never started at org.netbeans.modules.autoupdate.services.UpdateUnitProviderImpl.refresh(UpdateUnitProviderImpl.java:177)
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://raw.githubusercontent.com/wakatime/netbeans-wakatime/master/updates.xml:1:49: Document root element "module_updates", must match DOCTYPE root "null".
WARNING [org.netbeans.modules.autoupdate.updateprovider.AutoupdateCatalogParser]: https://raw.githubusercontent.com/wakatime/netbeans-wakatime/master/updates.xml:1:49: Document is invalid: no grammar found.
INFO [WakaTime]: Found new plugin version, updating...
INFO [WakaTime]: Update found: Jemmy[org.netbeans.modules.jemmy/3.24.1]
INFO [WakaTime]: Update found: Old Enumeration API[org.openide.util.enumerations/6.30.1]
INFO [WakaTime]: Update found: Performance Scripting Tests[org.netbeans.modules.performance.scripting/1.3.1]
INFO [WakaTime]: Update found: Scripting API Integration[org.netbeans.libs.jsr223/1.32.1]
INFO [WakaTime]: Update found: Actions SPI (Experimental)[org.netbeans.modules.spi.actions/1.24.1]
INFO [WakaTime]: Update found: INI File Editor Support[org.netbeans.modules.languages.ini/1.20.1]
INFO [WakaTime]: Update found: Compatibility APIs[org.openide.compat/6.33.1]
INFO [WakaTime]: Update found: Performance Web Tests[org.netbeans.modules.performance.web/1.3.1]
INFO [WakaTime]: Update found: Jelly Tools IDE[org.netbeans.modules.jellytools.ide/3.28.1.2]
INFO [WakaTime]: Update found: Generic Languages Framework[org.netbeans.modules.languages/1.117.1.2]
INFO [WakaTime]: Update found: Jelly Tools Platform[org.netbeans.modules.jellytools.platform/3.25.1]
INFO [WakaTime]: Update found: Performance Java Tests[org.netbeans.modules.performance.java/1.3.1]
INFO [WakaTime]: Update found: Jelly Tools Java[org.netbeans.modules.jellytools.java/3.27.1]
INFO [WakaTime]: Update found: Settings Options API[org.openide.options/6.32.1]
INFO [WakaTime]: Update found: Smack API[org.netbeans.libs.smack/3.23.1]
INFO [WakaTime]: Update found: Jelly Tools Enterprise[org.netbeans.modules.jellytools.enterprise/3.25.1]
INFO [WakaTime]: Update found: Performance Java EE Tests[org.netbeans.modules.performance.javaee/1.3.1]
INFO [WakaTime]: Update found: Performance Test Utilities[org.netbeans.modules.performance/1.3.1]
INFO [WakaTime]: Update found: Deprecated, old search API[org.openidex.util/3.43.1]
INFO [WakaTime]: Update found: Java Declarative Hints Test Support[org.netbeans.modules.java.hints.declarative.test/1.13.1.1.1]
INFO [WakaTime]: Update found: NetBeans in OSGi Runtime[org.netbeans.core.osgi/1.18.1]

Regards,

**Comment by alanhamlett** [comment]
The plugin now auto-downloads python if it's not already installed, so this might be fixed now.

**Comment by joeyc002** [comment]
Should it still automatically download python?

> CONFIG [WakaTime]: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
