### ISSUE TITLE
To long new version of plugin being downloaded

### ISSUE THREAD

**Issue by hexin** [wakatime/netbeans-wakatime#5]
I restarted netbeans after installation of the plugin and netbeans is trying to download new version of the plugin, but after several minutes there is still "Establishing a connection...".

**Comment by pietrondo** [comment]
same problem...

**Comment by pietrondo** [comment]
Arch linux 3.18.6-1-ARCH
and netbeans 8.0.2

**Comment by IgorPT** [comment]
same problem...

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Java: 1.8.0; Java HotSpot(TM) 64-Bit Server VM 25.0-b70
Runtime: Java(TM) SE Runtime Environment 1.8.0-b132
System: Windows 7 version 6.1 running on amd64; Cp1252; pt_PT (nb)

**Comment by winstonwp** [comment]
Same problem here...

NetBeans IDE 8.0.2 Buidl 201408251540
Ubuntu Linux 14.04

**Comment by alanhamlett** [comment]
Can you look in your IDE Log file (View -> IDE Log) and look for WakaTime log messages like this:
`INFO [WakaTime]: Checking for updates...`

The last `[WakaTime]` message should tell us at which point the update process is getting stuck.

**Comment by hexin** [comment]
SEVERE [WakaTime]: org.wakatime.netbeans.plugin.UpdateHandler$UpdateHandlerException: Missing Update Validator => cannot continue.
