### ISSUE TITLE
Sign plugin

### ISSUE THREAD

**Issue by jonathanlermitage** [wakatime/netbeans-wakatime#8]
Hi,
could you sign this plugin and ask for validation in order to see it in NetBeans plugins manager? (Tools | Plugins | Available plugins).
The signing process is described here: http://wiki.netbeans.org/DevFaqSignNbm

Regards,

**Comment by jonathanlermitage** [comment]
No?

**Comment by alanhamlett** [comment]
It already is signed. With e3aa30778c18f27a089d3fe4ed81298871ccfc84 I'm using a different alias, not sure if it wasn't in Available Plugins previously but it is now.
